### ISSUE TITLE
Concurrent Inserts to MySQL

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#54] opened 2020-03-11 14:23 UTC
```
(d:/MyProject/pkg/mod/github.com/uadmin/uadmin@v0.0.0-20200309025805-352ee701497c/db.go:516) 
[2020-03-11 16:58:14]  database is locked
```
Concurrent Inserts to MySQL seems to be not possible. Have anyone tried it?

**Comment by dxlvgcw** [comment] 2020-03-11 23:21
@MarErm27 I once had the database is locked issue but in SQLite. Never happened to me in MySQL. I did not try that yet.

@alphakitchown @Spotlight64 Did you guys tried that?

**Comment by alphakitchown** [comment] 2020-03-12 00:15
Neither do I. I checked the source code, concurrent inserts is doing on logs table.

**Comment by dxlvgcw** [comment] 2020-03-12 00:17
Okey.

@MarErm27 Can you post the code here how you do the concurrent inserts?

**Comment by MarErm27** [comment] 2020-03-12 06:45
> Okey.
> 
> @MarErm27 Can you post the code here how you do the concurrent inserts?

Sure! I'm sorry for not doing it at start.
Here I'm doing Ajax request

```
            $.ajax({
                method: "POST",
                data: {
                    Method: 'setTimeToStart',
                    UnixTimeToSet : unixTimeToSet
                },

                success: function (data) {
                    console.log("setAllActionStartTimeDone!")
                },
            });
```

Here what I do with this Ajax request at server side. I have a list of actions where I display time to start to do actions. After a period of time I need to change status of actions. The database is getting locked when variable "unixTimeToSet" is equal to current time. 

```
package views

import (
	"fmt"
	"math/rand"
	"net/http"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/MarErm27/webAppWithUAdmin/models"
	"github.com/uadmin/uadmin"
)

var wg sync.WaitGroup
var mtx sync.Mutex

// AdminHandler !
func AdminHandler(w http.ResponseWriter, r *http.Request) {
	r.URL.Path = strings.TrimPrefix(r.URL.Path, "/Admin")
	switch r.Method {
	case "GET":
	case "POST":
		Method := r.FormValue("Method")
		switch Method {
		case "setTimeToStart":
			UnixTimeToSet := r.FormValue("UnixTimeToSet")
			u, err := strconv.ParseInt(UnixTimeToSet, 10, 64)
			if err != nil {
				panic(err)
			}
			tm := time.Unix(u, 0)
			actions := []models.Actions{}
			uadmin.All(&actions)	
			t1 := time.Now()
			for i := range actions {
				wg.Add(1)
				uadmin.Preload(&actions[i])
				actions[i].actionsStart = tm
				mtx.Lock()
				uadmin.Save(&actions[i])
				mtx.Unlock()
				rand.Seed(time.Now().UnixNano())
				diffToChangeStatus := tm.Sub(t1)
				actionID := auctions[i].ActionID
				go changeStatus(diffToChangeStatus, actionID)
			}
			wg.Wait()
			fmt.Println("setAllActionsStartTime", UnixTimeToSet)
		}
	default:
		fmt.Fprintf(w, "Sorry, only GET and POST methods are supported.")
	}
}



func changeStatus(biddingStartNumber time.Duration, actionID string) { //, wg *sync.WaitGroup) {
	defer wg.Done()
	<-time.After(biddingStartNumber)
	action:= []models.Action{}
	uadmin.Filter(&action, "action_id = ?", actionID)
	action[0].Status = "Started"
	mtx.Lock()
	uadmin.Save(&action[0])
	mtx.Unlock()
}

func randFloats(min, max float64, n int) []float64 {
	res := make([]float64, n)
	for i := range res {
		res[i] = min + rand.Float64()*(max-min)
	}
	return res
}
```

**Comment by MarErm27** [comment] 2020-03-12 15:18
Forgot to say that I have 80 actions in MySql

**Comment by uadmin** [comment] 2020-07-28 05:00
On SQLite, the whole database will be locked white it is writing.

In MySQL, depending on the database engine (MyISAM or InnoDB) you will get different lock types. In MyISAM there is a table lock while the table is being written. In InnoDB, only the record will be locked during writing. This is really a database engine feature not a bug. Concurrent writing is blocked because data might be written incorrectly on a single record from two different updates.

So if you need concurrent inserts MyISAM might not be the best choice for you because it does table wide lock during writing. If this does not solve your problem please let me know.

**Comment by uadmin** [comment] 2020-07-30 04:31
@MarErm27 I'm closing this, feel free to reopen it if there is something more in here.

**Closed by uadmin** 2020-07-30 04:31 UTC
Labels: help wanted
